[project]
name = "keychain"
dynamic = ["version"]
keywords = ["password", "encryption", "keychain"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.13"

authors = [{ email = "dmitriyvasil@gmail.com" }]
maintainers = [{ email = "dmitriyvasil@gmail.com" }]
description = "Simple keychain service to store and retrieve secrets"

readme = "README.md"
license = { file = "LICENSE" }

dependencies = [
    "click>=8.3.0",
    "fastapi>=0.121.0",
    "loguru>=0.7.3",
    "pydantic>=2.12.4",
    "pydantic-settings[yaml]>=2.11.0",
    "uvicorn>=0.38.0",
]

[dependency-groups]
dev = ["ruff>=0.14.4"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/keychain/__init__.py"

[project.urls]
Homepage = "https://github.com/dmitriyVasilievich1986/keychain"

[tool.ruff]
line-length = 120

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Enable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
#
# This is currently disabled by default, but it is planned for this
# to be opt-out in the future.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in
# docstrings.
#
# This only has an effect when the `docstring-code-format` setting is
# enabled.
docstring-code-line-length = "dynamic"

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = [
    "A",     # flake8-builtins (A)
    "ARG",   # flake8-unused-arguments (ARG)
    "ASYNC", # flake8-async (ASYNC)
    "PTH",   # flake8-use-pathlib (PTH)
    "B",     # flake8-bugbear (B)
    "E",     # pycodestyle (E, W)
    "F",     # Pyflakes (F)
    "N",     # pep8-naming (N)
    "W",     # pycodestyle (E, W)
    "RUF",
    "SLF",   # flake8-self (SLF)
    "RET",   # flake8-return (RET)
    "Q",     # flake8-quotes (Q)
    "T20",   # flake8-print (T20)
    "COM",   # flake8-commas (COM)
    "D",     # pydocstyle (D)
    "FIX",   # flake8-fixme (FIX)
]
ignore = [
    "E712",
    "RUF001",
    "N817",
    "N814",
    "RUF100",
    "D100",
    "D101",
    "D104",
    "D401",
    "D203",
    "D213",
    "COM812",
]

extend-select = ["I"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.mccabe]
max-complexity = 18

[tool.ruff.lint.pycodestyle]
max-line-length = 120

[tool.ruff.lint.isort]
case-sensitive = false
combine-as-imports = true
force-sort-within-sections = false
known-first-party = ["cerebra_auth", "cerebra_common"]
lines-after-imports = -1
order-by-type = false
section-order = [
    "future",
    "standard-library",
    "third-party",
    "first-party",
    "local-folder",
]
known-third-party = []
