name: build-backend

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build release distributions
        run: |
          cd backend
          python -m pip install build
          python -m build
